### ISSUE TITLE
selectQueryParams return type

### ISSUE THREAD

**Issue by okeydoky** [ngneat/elf-ng-router-store#10]
Looks like when we call `selectQueryParams()` without providing names parameter, it will return original params from the router.  However, because the way the function is declared, it cause type error.  For example:
```
routerRepo.selectQueryParams().subscribe(params => {

  // type error below, params is inferred as string or string[]
  if (params && params['year']) {
    ...
  }
})
```

I will have do `const paramsMap = params as unknown as Params` to bypass the type check. Is this behavior by design? Am I doing something wrong? What should I do if want to work on all params?

Thanks!

**Comment by NetanelBasal** [comment]
@yackinn

**Comment by yackinn** [comment]
I'll check

**Comment by yackinn** [comment]
@okeydoky 
It's fixed.
You'll now get an object of all query params when no key is provided.
