### ISSUE TITLE
Installation Issue

### ISSUE THREAD

**Issue by okeydoky** [ngneat/elf-ng-router-store#12]
When I install the new version 1.0.3:

```
npm install @ngneat/elf-ng-router-store
```
node_modules/@ngneat/elf-ng-router-store  only contains package.json. Nothing is installed.

**Comment by NetanelBasal** [comment]
Done. @yackinn please check why it happend. I released it manually.

**Comment by okeydoky** [comment]
A minor suggestion. Angular 13 has rxjs dependency listed as:  `"rxjs": "^6.5.3 || ^7.4.0"` but the router store list rxjs dependency as `"rxjs": "~7.4.0"`

If there is no strong reason that store has to use 7.4.*, maybe update the dependency to ^7.4.0 to match angular will make it easier to install along side with angular.  For example, my rxjs is 7.5.5 in my angular 13 app, when I install the store I got dependency conflicts warning.

just a thought.

**Comment by NetanelBasal** [comment]
I don't think there is a valid reason to use RX v6, the upgrade should be seamless.
