### ISSUE TITLE
Getting data from lazy loaded child component doesn't work

### ISSUE THREAD

**Issue by hakimio** [ngneat/elf-ng-router-store#13]
### Is this a regression?

No

### Description

- Set `data` in your lazy loaded route:

![image](https://user-images.githubusercontent.com/768105/168611595-f1b98668-cd6f-4951-a4d5-ec710deba243.png)

- Subscribe to data changes:

![image](https://user-images.githubusercontent.com/768105/168611754-ed017565-143d-46f8-b6ef-2cfcf50cc167.png)

- If you run the application, logged data will be empty object: `{}`
- It seems that [`lastRouterState` is never updated in this case](https://github.com/ngneat/elf-ng-router-store/blob/fee2aeafe4ae4e03fa2d47f27abf5597c70a5475/libs/ng-router-store/src/lib/router.service.ts#L57).

### Please provide the environment you discovered this bug in

```true
@ngneat/elf-ng-router-store: 1.0.4
```

### Do you want to create a pull request?

No

**Comment by NetanelBasal** [comment]
Did you read the section about lazy loaded modules in the readme?

**Comment by hakimio** [comment]
If you mean, if I have set `paramsInheritanceStrategy: 'always'`, then yes, I have set it.
