### ISSUE TITLE
Missing license

### ISSUE THREAD

**Issue by LuisaBa** [ngneat/elf-ng-router-store#18]
Hi,

do you have a license for this project? At npm (https://www.npmjs.com/package/@ngneat/elf-ng-router-store/v/1.0.7?activeTab=readme) it says there is no license which means it is not allowed to use due to copyright issues.

**Comment by NetanelBasal** [comment]
https://github.com/ngneat/elf-ng-router-store/blob/master/LICENSE

**Comment by LuisaBa** [comment]
Is there a release planned soon again so that the file is also delivered with the install?

**Comment by NetanelBasal** [comment]
Sure

**Comment by NetanelBasal** [comment]
Done
