### ISSUE TITLE
Cannot find module '@ngneat/elf-ng-router-store'

### ISSUE THREAD

**Issue by ForzaMark** [ngneat/elf-ng-router-store#7]
### Is this a regression?

No

### Description

Hi Iam new to state management with Elf and would like to use your plugin because it perfectly fits my requirements of reacting to changes in the router

Steps to reproduce: 
1. create a new Angular project using angular cli
2. install elf using npx `npx @ngneat/elf-cli install`
   - I installed @ngneat/elf, @ngneat/elf-entities and @ngneat/elf-devtools. No external packages
3. install elf-ng-router-store by running `npm install @ngneat/elf-ng-router-store`
4. open app.module and add the following line 
   - `import { ElfNgRouterStoreModule } from '@elf/ng-router-store';` (from documentation)
   - this gives me the error: `Cannot find module '@elf/ng-router-store' or its corresponding type declarations.`

I think the import statement is not correct (so to say the reference in the documentation is not correct) but when I try to change the import to `import { ElfNgRouterStoreModule } from '@ngneat/elf-ng-router-store';` (which I think is the correct import) typescript still cant find the module (same error as given above)

When I inspect my node_modules under @ngneat/elf-ng-router-store it displays only a package.json which could be the mistake. 
![grafik](https://user-images.githubusercontent.com/28750031/149626324-b63faef7-6c24-4415-a4fb-3680768ee364.png)

Is this a bug or am I doing something wrong?

Nonetheless thanks for your work

### Please provide a link to a minimal reproduction of the bug

see description above

### Please provide the exception or error you saw

```true
Cannot find module '@elf/ng-router-store' or its corresponding type declarations.
```

### Please provide the environment you discovered this bug in

```true
Angular 12
Typescript 4.2.3
@ngneat/elf-ng-router-store 1.0.1
```

### Do you want to create a pull request?

No

**Comment by NetanelBasal** [comment]
@yackinn can you please check it?

**Comment by yackinn** [comment]
Yes, I'll check.

**Comment by yackinn** [comment]
@ForzaMark 
You're correct. The import should include elf.

`import { RouterRepository } from '@ngneat/elf-ng-router-store'`

**Comment by skumanduri** [comment]
The build seems to be broken and the NPM install command is only installing package.json and nothing else. That's why the below error is coming up;

_Cannot find module '@elf/ng-router-store' or its corresponding type declarations.__ 

Thanks for checking this.

**Comment by skblr** [comment]
The build process seems to be failing and the npm install is only installing an empty folder with just package.json. Nothing else is installed.

That's why the import is not finding the repository

_import { RouterRepository } from '@ngneat/elf-ng-router-store'_

Could you please check the build process? Thanks

**Comment by NetanelBasal** [comment]
Try the latest version

**Comment by skblr** [comment]
All good with the new version. Thanks a ton.
